"""Manufacture hand-inference training data by letting the bidding models play.

The hand model has to read *these* bots' auctions, not only human ones: an RL
run invents its own conventions (see rl/analyze.py), and a hand-guesser trained
on training.txt cannot interpret them. So the training data is generated by
rolling the existing models over random deals and keeping (deal, auction)
pairs -- rollouts only, no DD solving and no rewards, so this needs no endplay.

  python -m bidding_dt.hand.gen --out cache/gen --deals 200000 \
      --policy bc:runs/bc_small/best.pt --policy rl:runs/rl_tinyt/best.pt

Policies are league specs (rl/league.py): `random` | `bc:<ckpt>` | `rl:<ckpt>` |
`<ckpt>`, optionally weighted with `@w` (e.g. `random@0.2` for 20% noise
tables). Each deal's N-S pair and E-W pair draw a policy independently, so
tables mix systems as well as self-play.

The store layout matches data/parse.py's cache, so hand/data.py reads generated
stores and the human cache identically (and a training run can mix both).
"""

import argparse
import json
import time
from pathlib import Path

import numpy as np
from tqdm import tqdm

from ..data.hands import HAND_DIM
from ..data.parse import MAX_CALLS
from ..env.auction_env import AuctionBatch
from ..env.deals import random_deals
from ..rl.league import League
from ..rl.rollout import play_seat_policies
from ..train import pick_device
from .data import AuctionStore

STORE_FILES = ("hands", "calls", "lengths", "dealer", "vuln")


def split_weight(spec: str) -> tuple[str, float]:
    """'random@0.2' -> ('random', 0.2); a bare spec gets weight 1."""
    head, sep, tail = spec.rpartition("@")
    if sep:
        try:
            return head, float(tail)
        except ValueError:
            pass
    return spec, 1.0


def policy_pool(specs, device):
    """Load frozen policies from league specs -> (models, names, probs)."""
    if not specs:
        raise ValueError("no generator policies given (--policy SPEC)")
    league = League(device, persist_dir=None)
    for spec in specs:
        cleaned, weight = split_weight(spec)
        league.add_spec(cleaned, weight=weight)
    members = league.members
    return ([m.model for m in members], [m.name for m in members],
            league.probabilities())


def save_store(out_dir, hands, calls, lengths, dealer, vuln, policy=None,
               val_frac=0.01, test_frac=0.01, seed=4242, meta=None) -> Path:
    """Write a data/parse.py-compatible cache dir + deal splits."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    n = len(lengths)
    for name, arr in (("hands", hands), ("calls", calls), ("lengths", lengths),
                      ("dealer", dealer), ("vuln", vuln), ("policy", policy)):
        if arr is not None:
            np.save(out_dir / f"{name}.npy", arr)
    perm = np.random.default_rng(seed).permutation(n)
    n_val = int(n * val_frac)
    n_test = int(n * test_frac)
    np.save(out_dir / "test.npy", np.sort(perm[:n_test]))
    np.save(out_dir / "val.npy", np.sort(perm[n_test:n_test + n_val]))
    np.save(out_dir / "train.npy", np.sort(perm[n_test + n_val:]))
    info = {"num_deals": n, "max_calls": MAX_CALLS, "hand_dim": HAND_DIM,
            "seed": seed, "split": [1.0 - val_frac - test_frac, val_frac,
                                    test_frac],
            "mean_calls": round(float(lengths.mean()), 3),
            **(meta or {})}
    (out_dir / "meta.json").write_text(json.dumps(info, indent=2))
    return out_dir


def generate(out_dir, n_deals: int, specs, device, chunk: int = 256,
             greedy: bool = False, temp: float = 1.0, amp: bool = False,
             val_frac: float = 0.01, test_frac: float = 0.01, seed: int = 4242,
             progress: bool = True) -> AuctionStore:
    """Roll `n_deals` random deals with the given policies -> AuctionStore."""
    policies, names, probs = policy_pool(specs, device)
    rng = np.random.default_rng(seed)
    hands = np.zeros((n_deals, 4, HAND_DIM), dtype=np.uint8)
    calls = np.zeros((n_deals, MAX_CALLS), dtype=np.uint8)
    lengths = np.zeros(n_deals, dtype=np.uint8)
    dealer = np.zeros(n_deals, dtype=np.uint8)
    vuln = np.zeros(n_deals, dtype=np.uint8)
    policy = np.zeros((n_deals, 4), dtype=np.int8)

    t0 = time.time()
    done = 0
    bar = tqdm(total=n_deals, unit="deal", disable=not progress)
    while done < n_deals:
        b = min(chunk, n_deals - done)
        deals = random_deals(rng, b)
        dl = rng.integers(0, 4, b)
        vn = rng.integers(0, 4, b)
        seat_policy = np.empty((b, 4), dtype=np.int64)
        seat_policy[:, 0] = seat_policy[:, 2] = rng.choice(len(policies), b, p=probs)
        seat_policy[:, 1] = seat_policy[:, 3] = rng.choice(len(policies), b, p=probs)
        env = AuctionBatch(deals, dl, vn)
        play_seat_policies(env, policies, seat_policy, device, greedy=greedy,
                           temp=temp, amp=amp)
        s = slice(done, done + b)
        hands[s] = np.stack([d.encoded for d in deals])
        calls[s] = env.calls
        lengths[s] = env.n_calls
        dealer[s] = dl
        vuln[s] = vn
        policy[s] = seat_policy
        done += b
        bar.update(b)
    bar.close()

    out_dir = save_store(out_dir, hands, calls, lengths, dealer, vuln,
                         policy=policy, val_frac=val_frac, test_frac=test_frac,
                         seed=seed,
                         meta={"generated": True, "policies": names,
                               "weights": [round(float(p), 4) for p in probs],
                               "temp": temp, "greedy": greedy,
                               "seconds": round(time.time() - t0, 1)})
    print(f"generated {n_deals} deals -> {out_dir} "
          f"(mean {lengths.mean():.2f} calls, {time.time() - t0:.1f}s)")
    return AuctionStore.load(out_dir, name=out_dir.name)


def load_or_generate(out_dir, n_deals: int, specs, device, reuse: bool = False,
                     **kwargs) -> AuctionStore:
    """Reuse an existing store when `reuse`, else (re)generate it."""
    path = Path(out_dir)
    if reuse and all((path / f"{f}.npy").exists() for f in STORE_FILES) \
            and (path / "train.npy").exists():
        print(f"reusing generated store {path}")
        return AuctionStore.load(path, name=path.name)
    if n_deals <= 0:
        raise ValueError(f"no store at {path} and gen.deals={n_deals}")
    return generate(path, n_deals, specs, device, **kwargs)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="cache/gen", help="store directory")
    ap.add_argument("--policy", action="append", default=[], metavar="SPEC[@W]",
                    help="generator policy, repeatable: random | bc:<ckpt> | "
                         "rl:<ckpt> | <ckpt>, optional @weight")
    ap.add_argument("--deals", type=int, default=100_000)
    ap.add_argument("--chunk", type=int, default=256)
    ap.add_argument("--temp", type=float, default=1.0)
    ap.add_argument("--greedy", action="store_true",
                    help="deterministic rollouts (default: sample at --temp)")
    ap.add_argument("--val-frac", type=float, default=0.01)
    ap.add_argument("--test-frac", type=float, default=0.01)
    ap.add_argument("--seed", type=int, default=4242)
    ap.add_argument("--device", default=None)
    ap.add_argument("--cpu-bf16", action="store_true",
                    help="bf16 autocast for the rollout forwards (AVX512/AMX)")
    args = ap.parse_args()

    device = pick_device(args.device)
    generate(args.out, args.deals, args.policy, device, chunk=args.chunk,
             greedy=args.greedy, temp=args.temp, amp=args.cpu_bf16,
             val_frac=args.val_frac, test_frac=args.test_frac, seed=args.seed)


if __name__ == "__main__":
    main()
